// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualWallet.DataAccess;

#nullable disable

namespace VirtualWallet.DataAccess.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20230719124924_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Balance", b =>
                {
                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CurrencyId", "WalletId");

                    b.HasIndex("WalletId");

                    b.ToTable("Balances");

                    b.HasData(
                        new
                        {
                            CurrencyId = 1,
                            WalletId = 1,
                            Amount = 10000m
                        },
                        new
                        {
                            CurrencyId = 2,
                            WalletId = 2,
                            Amount = 10000m
                        },
                        new
                        {
                            CurrencyId = 3,
                            WalletId = 3,
                            Amount = 10000m
                        },
                        new
                        {
                            CurrencyId = 1,
                            WalletId = 4,
                            Amount = 10200m
                        },
                        new
                        {
                            CurrencyId = 2,
                            WalletId = 5,
                            Amount = 102400m
                        },
                        new
                        {
                            CurrencyId = 1,
                            WalletId = 6,
                            Amount = 102004m
                        },
                        new
                        {
                            CurrencyId = 3,
                            WalletId = 7,
                            Amount = 50200m
                        },
                        new
                        {
                            CurrencyId = 5,
                            WalletId = 8,
                            Amount = 1023230m
                        },
                        new
                        {
                            CurrencyId = 4,
                            WalletId = 9,
                            Amount = 102000000m
                        });
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EUR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BGN"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JPY"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CFH"
                        });
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blocked"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("WalletId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5643),
                            Email = "gosho@gmail.com",
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Georgiev",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "goshoXx123",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5682),
                            Email = "Barekov@gmail.com",
                            FirstName = "Nikolai",
                            IsDeleted = false,
                            LastName = "Barekov",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "BarekaXx123",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5686),
                            Email = "Uzunkata@gmail.com",
                            FirstName = "Shtilian",
                            IsDeleted = false,
                            LastName = "Uzunov",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "Uzunkata",
                            WalletId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5689),
                            Email = "Cvetan@gmail.com",
                            FirstName = "Vladislav",
                            IsDeleted = false,
                            LastName = "Cvetanov",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "Cvete123",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5691),
                            Email = "Kostev@gmail.com",
                            FirstName = "Kosta",
                            IsDeleted = false,
                            LastName = "Kostev",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "BrainDamage123",
                            WalletId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5695),
                            Email = "Admin@gmail.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "Adminov",
                            Password = "MTIz",
                            RoleId = 3,
                            Username = "Admin",
                            WalletId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5698),
                            Email = "Andrea@gmail.com",
                            FirstName = "Andrea",
                            IsDeleted = false,
                            LastName = "Paynera",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "TopAndreika",
                            WalletId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5701),
                            Email = "Emanuela@gmail.com",
                            FirstName = "Emanuela",
                            IsDeleted = false,
                            LastName = "Paynera",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "TopEmanuelka",
                            WalletId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5703),
                            Email = "Katrin@gmail.com",
                            FirstName = "Katrin",
                            IsDeleted = false,
                            LastName = "lilova",
                            Password = "MTIz",
                            RoleId = 2,
                            Username = "Katrin",
                            WalletId = 9
                        });
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5709),
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5714),
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5717),
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5719),
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5721),
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5724),
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5726),
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5728),
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2023, 7, 19, 15, 49, 23, 658, DateTimeKind.Local).AddTicks(5730),
                            IsDeleted = false,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Balance", b =>
                {
                    b.HasOne("VirtualWallet.DataAccess.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWallet.DataAccess.Models.Wallet", "Wallet")
                        .WithMany("Balances")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("VirtualWallet.DataAccess.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWallet.DataAccess.Models.User", "Recipient")
                        .WithMany("Incoming")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VirtualWallet.DataAccess.Models.User", "Sender")
                        .WithMany("Outgoing")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.User", b =>
                {
                    b.HasOne("VirtualWallet.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWallet.DataAccess.Models.Wallet", "Wallet")
                        .WithOne("User")
                        .HasForeignKey("VirtualWallet.DataAccess.Models.User", "WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.User", b =>
                {
                    b.Navigation("Incoming");

                    b.Navigation("Outgoing");
                });

            modelBuilder.Entity("VirtualWallet.DataAccess.Models.Wallet", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
